name: Test code, build Containers for Production, push to Dockerhub & deploy into DigitalOcean Droplet.

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-back: #job1
    name: Backend Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x, 18.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup   
        run: npm install

      - name: Run tests
        run: npm run test

  build-and-deploy-back: #job2
    needs: test-back
    name: Build and Deploy Back
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mkidea-api:latest,${{ secrets.DOCKER_USERNAME }}/mkidea-api:${{ github.sha }}
      - name: Deploy to Digital Ocean via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          script: |
            docker kill $(docker ps -q)
            docker rm $(docker ps -a -q)
            docker rmi $(docker images -q)
            cd mkidea-api
            docker compose pull
            docker compose down || true
            docker compose up -d